# Generated by Django 5.1.3 on 2025-08-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
